// Supabase Edge Function: generate-program
//
// Phase C of the v1.2 assessment pivot. Takes a user's PelvicFloorIndex
// measurements + lifestyle answers and returns a structured 8-week
// ProgramDay[] generated by Claude Haiku 4.5.
//
// Called by lib/program.ts buildProgram() once at onboarding (the plan
// chose "AI once at onboarding, rule-based retests" — see
// /root/.claude/plans/relay-the-plan-for-stateless-gadget.md).
//
// Deploy:
//   supabase functions deploy generate-program
//
// Required secrets:
//   ANTHROPIC_API_KEY            — sk-ant-api03-...  (set via `supabase secrets set`)
//   SUPABASE_URL                 — auto-injected
//   SUPABASE_SERVICE_ROLE_KEY    — auto-injected
//
// Auth: the caller's Supabase JWT must be in the Authorization header.
// We verify the user exists (no per-user authorization required beyond
// being signed in — generating a program for yourself is a free action).

import { serve } from 'https://deno.land/std@0.208.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.46.0';
import Anthropic from 'npm:@anthropic-ai/sdk@^0.65.0';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

// IMPORTANT: keep in lockstep with lib/exercises.ts EXERCISES keys.
// The client resolves these slugs to ExerciseTemplate locally, so any
// slug the AI emits that isn't in this list will be dropped client-side.
const VALID_SLUGS = [
  // Original v1.1 catalog — pure pelvic-floor work
  'quick_flicks',
  'short_holds',
  'long_holds',
  'endurance_ladder',
  'quick_discreet',
  // v1.2 expansion — holistic palette
  'reverse_kegels',
  'pulse_hold_combo',
  'adductor_squeeze',
  'glute_bridge',
  'bird_dog',
  'deep_squat_breath',
  'tabletop_marches',
] as const;

const SYSTEM_PROMPT = `You are a clinical exercise physiologist specialising in pelvic-floor training. Generate a personalised 8-week program from a user's assessment.

INPUTS
- measurements.pulsesIn30s: contractions in 30 s (10 = sedentary, 80 = elite)
- measurements.maxHoldS: max sustained contraction in s (3 = very weak, 90 = elite)
- answers.ageBand: 18-25 | 26-35 | 36-45 | 46-55 | 56-65 | 66+
- answers.strengthDaysPerWeek: 0-7
- answers.cardioDaysPerWeek: 0-7
- answers.intimacyPerWeek: 0-7
- level: beginner | intermediate | advanced

EXERCISE CATALOG (use only these slugs)
Pure pelvic-floor work (foundational):
- quick_flicks: 1 s on, 1 s off rapid contractions. Trains fast-twitch fibres. Typical 2 × 10. Position: any.
- short_holds: 1 s squeeze, 3 s hold, 3 s release. Foundational contraction control. Typical 2 × 8. Position: any.
- long_holds: 1.5 s squeeze, 8 s hold, 5 s release. Builds slow-twitch endurance. Typical 2 × 5. Position: any.
- endurance_ladder: 1.5 s squeeze, 5 s hold, 5 s release. Progressive holds for cardio adaptation. Typical 1 × 5. Position: any.
- quick_discreet: 1 s on, 1.5 s off. Stealth-friendly short session. Typical 1 × 5. Position: any.

Release / expansion work:
- reverse_kegels: Active downward release (gentle bear-down). Trains the OPPOSITE of a contraction — full relaxation and downward expansion. Typical 2 × 5. Position: supine.

Combined fast + slow patterns:
- pulse_hold_combo: 5 quick pulses, 4 s hold, 5 more pulses. Hybrid of fast-twitch speed + slow-twitch endurance in one set. Typical 2 × 6. Position: any.

Synergist + posterior-chain integration (recruit adjacent muscles):
- adductor_squeeze: Inner-thigh squeeze with pelvic-floor co-contraction. Adductors fire reflexively with the floor. Typical 2 × 10. Position: supine.
- glute_bridge: Hip bridge held at the top with floor activation. Builds posterior-chain support. Typical 2 × 8. Position: supine.
- bird_dog: Quadruped opposite arm + leg extension with floor cue. Deep-core stabiliser. Each rep is one side, so 2 × 10 = 5 per side. Position: quadruped.
- tabletop_marches: Supine tabletop hip flexion alternating sides with floor brace. Deep-core integration. Each rep is one side. Typical 2 × 10. Position: supine.

Mobility + breath:
- deep_squat_breath: Deep squat hold with diaphragmatic breathing; downshift the floor on each exhale. Pairs mobility with active relaxation. Typical 1 × 5. Position: standing.

PROGRAM DESIGN RULES
1. Output exactly 56 day objects (8 weeks × 7 days), dayIndex 0-55.
2. Include at least 1 rest day per week (exercises: [], targetDurationS: 0).
3. Never repeat the same exercise 3 days in a row.
4. Difficulty ramps from week 1 (foundational) to week 8 (peak intensity).
5. Age calibration:
   - 18-25: aggressive ramp, higher peak intensity
   - 26-45: standard ramp
   - 46-65: gradual ramp, extra recovery days
   - 66+: gentle ramp, emphasise control over peak load
6. Lifestyle calibration:
   - High strength + cardio days: tolerate higher session intensity, shorter sessions OK
   - Sedentary (0-1 days/week): longer warmup blocks, lower peak
   - High intimacy frequency: prioritise both endurance and control evenly
7. targetDurationS per training day: 240-360 s (4-6 min). 0 for rest days.
8. sets: 1-5. reps: 1-20.
9. Holistic variety — within each week, prefer a mix of categories (pure floor work + at least one synergist/posterior-chain or release/mobility exercise) rather than 7 days of pure Kegel-style work.
10. Position grouping — when a day mixes exercises, prefer same-position groupings (e.g. all supine, or floor + standing) over forcing the user to repeatedly change setup mid-session. The catalog tags each exercise's position; 'any' fits with anything.

OUTPUT
Return STRICT JSON. Include 3 short "focuses" (≤ 8 words each) that name the program's emphasis — these appear on the user's plan-preview screen. Examples: "Endurance — long holds + ladder", "Pulse speed — quick flicks 3×/week", "Posterior chain — adductor + glute work".`;

const PROGRAM_SCHEMA = {
  type: 'object',
  properties: {
    weeks: { type: 'integer', const: 8 },
    focuses: {
      type: 'array',
      items: { type: 'string' },
      minItems: 3,
      maxItems: 3,
    },
    days: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          dayIndex: { type: 'integer', minimum: 0, maximum: 55 },
          targetDurationS: { type: 'integer', minimum: 0, maximum: 1200 },
          exercises: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                slug: { type: 'string', enum: VALID_SLUGS as readonly string[] },
                sets: { type: 'integer', minimum: 1, maximum: 5 },
                reps: { type: 'integer', minimum: 1, maximum: 20 },
              },
              required: ['slug', 'sets', 'reps'],
              additionalProperties: false,
            },
          },
        },
        required: ['dayIndex', 'targetDurationS', 'exercises'],
        additionalProperties: false,
      },
    },
  },
  required: ['weeks', 'focuses', 'days'],
  additionalProperties: false,
};

type GenerateProgramInput = {
  measurements: { pulsesIn30s: number; maxHoldS: number };
  answers: {
    ageBand: string;
    strengthDaysPerWeek: number;
    cardioDaysPerWeek: number;
    intimacyPerWeek: number;
  };
  level: 'beginner' | 'intermediate' | 'advanced';
};

function isValidInput(body: unknown): body is GenerateProgramInput {
  if (!body || typeof body !== 'object') return false;
  const b = body as Record<string, unknown>;
  const m = b.measurements as Record<string, unknown> | undefined;
  const a = b.answers as Record<string, unknown> | undefined;
  return (
    !!m &&
    typeof m.pulsesIn30s === 'number' &&
    typeof m.maxHoldS === 'number' &&
    !!a &&
    typeof a.ageBand === 'string' &&
    typeof a.strengthDaysPerWeek === 'number' &&
    typeof a.cardioDaysPerWeek === 'number' &&
    typeof a.intimacyPerWeek === 'number' &&
    (b.level === 'beginner' || b.level === 'intermediate' || b.level === 'advanced')
  );
}

function formatUserMessage(input: GenerateProgramInput): string {
  return JSON.stringify(input, null, 2);
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: CORS_HEADERS });
  }
  if (req.method !== 'POST') {
    return jsonResponse({ ok: false, error: 'Method not allowed' }, 405);
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const anthropicKey = Deno.env.get('ANTHROPIC_API_KEY');
  if (!supabaseUrl || !serviceRoleKey || !anthropicKey) {
    return jsonResponse({ ok: false, error: 'Server not configured' }, 500);
  }

  const auth = req.headers.get('Authorization');
  if (!auth) {
    return jsonResponse({ ok: false, error: 'Missing Authorization' }, 401);
  }

  // Verify the caller has a valid Supabase JWT.
  const userClient = createClient(supabaseUrl, serviceRoleKey, {
    global: { headers: { Authorization: auth } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData.user) {
    return jsonResponse({ ok: false, error: 'Invalid session' }, 401);
  }

  // Enforce AI-consent server-side before any PII reaches Anthropic.
  // Lifestyle answers (incl. intimacy frequency) and measurements are
  // sensitive — a missing/null ai_consent_at means the user has not
  // agreed to forward this data, and we refuse rather than trust the
  // client to gate. See supabase/migrations/0006_ai_consent.sql.
  const { data: profile, error: profileErr } = await userClient
    .from('profiles')
    .select('ai_consent_at')
    .eq('id', userData.user.id)
    .maybeSingle();
  if (profileErr) {
    console.error('generate-program · profile lookup failed:', profileErr);
    return jsonResponse({ ok: false, error: 'Profile lookup failed' }, 500);
  }
  if (!profile?.ai_consent_at) {
    return jsonResponse(
      { ok: false, error: 'AI consent required', code: 'consent_required' },
      403,
    );
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ ok: false, error: 'Invalid JSON body' }, 400);
  }
  if (!isValidInput(body)) {
    return jsonResponse({ ok: false, error: 'Invalid input shape' }, 400);
  }

  const client = new Anthropic({ apiKey: anthropicKey });

  let response;
  try {
    response = await client.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 8000,
      // cache_control on the system prompt — currently sub-minimum (≈600
      // tokens vs the 4096-token Haiku threshold), so the cache silently
      // won't hit until Phase D expands the catalog. Leaving the directive
      // in place so it activates automatically when that lands.
      system: [
        {
          type: 'text',
          text: SYSTEM_PROMPT,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: [{ role: 'user', content: formatUserMessage(body) }],
      // Constrain output to the program schema. The SDK validates server-side
      // and returns 400 if the model can't produce a matching shape.
      output_config: {
        format: {
          type: 'json_schema',
          schema: PROGRAM_SCHEMA,
        },
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown Anthropic error';
    console.error('generate-program · Anthropic call failed:', msg);
    return jsonResponse({ ok: false, error: `LLM error: ${msg}` }, 502);
  }

  // Guard on stop_reason BEFORE parsing — output_config.format guarantees
  // schema-conformant JSON only on stop_reason === 'end_turn'. A 'refusal'
  // means Claude declined (returns no JSON), 'max_tokens' means truncation
  // mid-document (JSON.parse will throw). Distinguishing them gives ops a
  // real signal instead of "Invalid LLM JSON" for every failure mode.
  if (response.stop_reason === 'refusal') {
    console.warn('generate-program · model refused:', response.stop_reason);
    return jsonResponse(
      { ok: false, error: 'Model declined to generate this program' },
      502,
    );
  }
  if (response.stop_reason === 'max_tokens') {
    console.warn('generate-program · output truncated at max_tokens');
    return jsonResponse(
      { ok: false, error: 'Program too large — output truncated' },
      502,
    );
  }

  const block = response.content.find((b) => b.type === 'text');
  if (!block || block.type !== 'text') {
    console.error('generate-program · no text block in response:', response);
    return jsonResponse({ ok: false, error: 'Empty LLM response' }, 502);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(block.text);
  } catch (err) {
    console.error('generate-program · JSON parse failed:', err, block.text);
    return jsonResponse({ ok: false, error: 'Invalid LLM JSON' }, 502);
  }

  return jsonResponse({ ok: true, program: parsed, usage: response.usage });
});
