// Supabase Edge Function: generate-program
//
// Phase C of the v1.2 assessment pivot. Takes a user's PelvicFloorIndex
// measurements + lifestyle answers and returns a structured 8-week
// ProgramDay[] generated by Claude Haiku 4.5.
//
// Called by lib/program.ts buildProgram() once at onboarding (the plan
// chose "AI once at onboarding, rule-based retests" — see
// /root/.claude/plans/relay-the-plan-for-stateless-gadget.md).
//
// Deploy:
//   supabase functions deploy generate-program
//
// Required secrets:
//   ANTHROPIC_API_KEY            — sk-ant-api03-...  (set via `supabase secrets set`)
//   SUPABASE_URL                 — auto-injected
//   SUPABASE_SERVICE_ROLE_KEY    — auto-injected
//
// Auth: the caller's Supabase JWT must be in the Authorization header.
// We verify the user exists (no per-user authorization required beyond
// being signed in — generating a program for yourself is a free action).

import { serve } from 'https://deno.land/std@0.208.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.46.0';
import Anthropic from 'npm:@anthropic-ai/sdk@^0.40.0';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const VALID_SLUGS = [
  'quick_flicks',
  'short_holds',
  'long_holds',
  'endurance_ladder',
  'quick_discreet',
] as const;

const SYSTEM_PROMPT = `You are a clinical exercise physiologist specialising in pelvic-floor training. Generate a personalised 8-week program from a user's assessment.

INPUTS
- measurements.pulsesIn30s: contractions in 30 s (10 = sedentary, 80 = elite)
- measurements.maxHoldS: max sustained contraction in s (3 = very weak, 90 = elite)
- answers.ageBand: 18-25 | 26-35 | 36-45 | 46-55 | 56-65 | 66+
- answers.strengthDaysPerWeek: 0-7
- answers.cardioDaysPerWeek: 0-7
- answers.intimacyPerWeek: 0-7
- level: beginner | intermediate | advanced

EXERCISE CATALOG (use only these slugs)
- quick_flicks: 1 s on, 1 s off rapid contractions. Trains fast-twitch fibres. Typical 2 × 10.
- short_holds: 1 s squeeze, 3 s hold, 3 s release. Foundational contraction control. Typical 2 × 8.
- long_holds: 1.5 s squeeze, 8 s hold, 5 s release. Builds slow-twitch endurance. Typical 2 × 5.
- endurance_ladder: 1.5 s squeeze, 5 s hold, 5 s release. Cardio adaptation. Typical 1 × 5.
- quick_discreet: 1 s on, 1.5 s off. Stealth-friendly short session. Typical 1 × 5.

PROGRAM DESIGN RULES
1. Output exactly 56 day objects (8 weeks × 7 days), dayIndex 0-55.
2. Include at least 1 rest day per week (exercises: [], targetDurationS: 0).
3. Never repeat the same exercise 3 days in a row.
4. Difficulty ramps from week 1 (foundational) to week 8 (peak intensity).
5. Age calibration:
   - 18-25: aggressive ramp, higher peak intensity
   - 26-45: standard ramp
   - 46-65: gradual ramp, extra recovery days
   - 66+: gentle ramp, emphasise control over peak load
6. Lifestyle calibration:
   - High strength + cardio days: tolerate higher session intensity, shorter sessions OK
   - Sedentary (0-1 days/week): longer warmup blocks, lower peak
   - High intimacy frequency: prioritise both endurance and control evenly
7. targetDurationS per training day: 240-360 s (4-6 min). 0 for rest days.
8. sets: 1-5. reps: 1-20.

OUTPUT
Return STRICT JSON. Include 3 short "focuses" (≤ 8 words each) that name the program's emphasis — these appear on the user's plan-preview screen. Examples: "Endurance — long holds + ladder", "Pulse speed — quick flicks 3×/week", "Posterior chain — adductor + glute work".`;

const PROGRAM_SCHEMA = {
  type: 'object',
  properties: {
    weeks: { type: 'integer', const: 8 },
    focuses: {
      type: 'array',
      items: { type: 'string' },
      minItems: 3,
      maxItems: 3,
    },
    days: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          dayIndex: { type: 'integer', minimum: 0, maximum: 55 },
          targetDurationS: { type: 'integer', minimum: 0, maximum: 1200 },
          exercises: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                slug: { type: 'string', enum: VALID_SLUGS as readonly string[] },
                sets: { type: 'integer', minimum: 1, maximum: 5 },
                reps: { type: 'integer', minimum: 1, maximum: 20 },
              },
              required: ['slug', 'sets', 'reps'],
              additionalProperties: false,
            },
          },
        },
        required: ['dayIndex', 'targetDurationS', 'exercises'],
        additionalProperties: false,
      },
    },
  },
  required: ['weeks', 'focuses', 'days'],
  additionalProperties: false,
};

type GenerateProgramInput = {
  measurements: { pulsesIn30s: number; maxHoldS: number };
  answers: {
    ageBand: string;
    strengthDaysPerWeek: number;
    cardioDaysPerWeek: number;
    intimacyPerWeek: number;
  };
  level: 'beginner' | 'intermediate' | 'advanced';
};

function isValidInput(body: unknown): body is GenerateProgramInput {
  if (!body || typeof body !== 'object') return false;
  const b = body as Record<string, unknown>;
  const m = b.measurements as Record<string, unknown> | undefined;
  const a = b.answers as Record<string, unknown> | undefined;
  return (
    !!m &&
    typeof m.pulsesIn30s === 'number' &&
    typeof m.maxHoldS === 'number' &&
    !!a &&
    typeof a.ageBand === 'string' &&
    typeof a.strengthDaysPerWeek === 'number' &&
    typeof a.cardioDaysPerWeek === 'number' &&
    typeof a.intimacyPerWeek === 'number' &&
    (b.level === 'beginner' || b.level === 'intermediate' || b.level === 'advanced')
  );
}

function formatUserMessage(input: GenerateProgramInput): string {
  return JSON.stringify(input, null, 2);
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: CORS_HEADERS });
  }
  if (req.method !== 'POST') {
    return jsonResponse({ ok: false, error: 'Method not allowed' }, 405);
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const anthropicKey = Deno.env.get('ANTHROPIC_API_KEY');
  if (!supabaseUrl || !serviceRoleKey || !anthropicKey) {
    return jsonResponse({ ok: false, error: 'Server not configured' }, 500);
  }

  const auth = req.headers.get('Authorization');
  if (!auth) {
    return jsonResponse({ ok: false, error: 'Missing Authorization' }, 401);
  }

  // Verify the caller has a valid Supabase JWT.
  const userClient = createClient(supabaseUrl, serviceRoleKey, {
    global: { headers: { Authorization: auth } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData.user) {
    return jsonResponse({ ok: false, error: 'Invalid session' }, 401);
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ ok: false, error: 'Invalid JSON body' }, 400);
  }
  if (!isValidInput(body)) {
    return jsonResponse({ ok: false, error: 'Invalid input shape' }, 400);
  }

  const client = new Anthropic({ apiKey: anthropicKey });

  let response;
  try {
    response = await client.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 8000,
      // cache_control on the system prompt — currently sub-minimum (≈600
      // tokens vs the 4096-token Haiku threshold), so the cache silently
      // won't hit until Phase D expands the catalog. Leaving the directive
      // in place so it activates automatically when that lands.
      system: [
        {
          type: 'text',
          text: SYSTEM_PROMPT,
          cache_control: { type: 'ephemeral' },
        },
      ],
      messages: [{ role: 'user', content: formatUserMessage(body) }],
      // Constrain output to the program schema. The SDK validates server-side
      // and returns 400 if the model can't produce a matching shape.
      output_config: {
        format: {
          type: 'json_schema',
          schema: PROGRAM_SCHEMA,
        },
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown Anthropic error';
    console.error('generate-program · Anthropic call failed:', msg);
    return jsonResponse({ ok: false, error: `LLM error: ${msg}` }, 502);
  }

  // The structured-output path returns content as a single text block whose
  // text is the JSON. Parse it; if anything is off, surface a 502.
  const block = response.content.find((b) => b.type === 'text');
  if (!block || block.type !== 'text') {
    console.error('generate-program · no text block in response:', response);
    return jsonResponse({ ok: false, error: 'Empty LLM response' }, 502);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(block.text);
  } catch (err) {
    console.error('generate-program · JSON parse failed:', err, block.text);
    return jsonResponse({ ok: false, error: 'Invalid LLM JSON' }, 502);
  }

  return jsonResponse({ ok: true, program: parsed, usage: response.usage });
});
